# Generated by Django 3.0.3 on 2020-03-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0025_fuelprices_fuel_price'),
        ('users', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gas_station_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.GasolineStation'),
        ),
    ]
