# Generated by Django 3.0.3 on 2020-02-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelpricing',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='gasstations',
            options={'ordering': ['-name']},
        ),
    ]
