# Generated by Django 3.0.3 on 2020-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0003_auto_20200227_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstations',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gasstations',
            name='volume_of_gasoline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
