# Generated by Django 3.0.3 on 2020-02-28 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gasolinestation', '0004_auto_20200228_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstations',
            name='site_staff',
            field=models.ManyToManyField(blank=True, related_name='site_staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
