# Generated by Django 3.0.3 on 2020-03-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0006_auto_20200228_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstations',
            old_name='created_by_staff',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='gasstations',
            old_name='updated_by_manager',
            new_name='updated_by',
        ),
    ]
