# Generated by Django 3.0.3 on 2020-03-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0008_importantinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfFuel',
            fields=[
                ('importantinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gasolinestation.ImportantInfo')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('gasolinestation.importantinfo',),
        ),
    ]
