# Generated by Django 3.0.3 on 2020-03-03 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0009_typeoffuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
