# Generated by Django 3.0.3 on 2020-03-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0010_auto_20200303_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceManagement',
            fields=[
                ('importantinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gasolinestation.ImportantInfo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('gas_station_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.GasStations')),
                ('type_of_fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.TypeOfFuel')),
            ],
            bases=('gasolinestation.importantinfo',),
        ),
    ]
