# Generated by Django 3.0.3 on 2020-03-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0011_pricemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('gas_station_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.GasStations')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.PriceManagement')),
                ('type_of_fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.TypeOfFuel')),
            ],
        ),
    ]
