# Generated by Django 3.0.3 on 2020-03-04 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0013_auto_20200304_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsales',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsales',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactionsales',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionsales',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
