# Generated by Django 3.0.3 on 2020-03-04 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0014_auto_20200304_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsales',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
