# Generated by Django 3.0.3 on 2020-03-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0016_auto_20200307_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstations',
            name='volume_of_gasoline',
        ),
    ]
