# Generated by Django 3.0.3 on 2020-03-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0018_auto_20200307_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolineStation',
            fields=[
                ('importantinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gasolinestation.ImportantInfo')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
            bases=('gasolinestation.importantinfo',),
        ),
    ]
