# Generated by Django 3.0.3 on 2020-03-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0021_fuelprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('importantinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gasolinestation.ImportantInfo')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('dispensed_liter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.FuelPrices')),
                ('gas_station_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gasolinestation.GasolineStation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('gasolinestation.importantinfo',),
        ),
    ]
