# Generated by Django 3.0.3 on 2020-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0022_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstations',
            name='fuels',
        ),
        migrations.RemoveField(
            model_name='gasstations',
            name='price_management_flexibility',
        ),
        migrations.RemoveField(
            model_name='gasstations',
            name='sales',
        ),
        migrations.AddField(
            model_name='gasstations',
            name='fuel_prices',
            field=models.ManyToManyField(blank=True, to='gasolinestation.FuelPrices'),
        ),
        migrations.DeleteModel(
            name='TransactionSales',
        ),
    ]
