# Generated by Django 3.0.3 on 2020-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinestation', '0024_auto_20200311_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelprices',
            name='fuel_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
